[versions]
ktor = "3.3.2"
google-gson = "2.11.0"
google-ortools = "9.14.6206"

[libraries]
ktor-client-core = { module="io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module="io.ktor:ktor-client-okhttp", version.ref = "ktor" }
google-gson = { module="com.google.code.gson:gson", version.ref = "google-gson" }
google-ortools = { module = "com.google.ortools:ortools-java", version.ref = "google-ortools" }
